### ISSUE TITLE
postgresql 运行后无法获取数据表列表解决方法

### ISSUE THREAD

**Issue by SunZongming** [astarring/mybatis-generator-gui#100]
**在 DbUtil.java 中的第 70 行**进行修改：
原内容：
`//rs = md.getTables(null, config.getUsername().toUpperCase(), null, null);`
修改后：
`rs = md.getTables(null, "%", "%", new String[] {"TABLE", "VIEW"});`

这样修改后就可以显示出 postgresql 的数据表，并且 MySQL 的也可以正常的显示。

**Comment by astarring** [comment]
thanks， merged
