### ISSUE TITLE
没有主清单属性

### ISSUE THREAD

**Issue by baiyapeng** [astarring/mybatis-generator-gui#11]
OS：Win7×64
打包工具：apache-maven-3.3.9
JDK：jdk-8u101-windows-x64
DB：MySql
`C:\Users\baiyapeng\.m2\repository\com\zzg\mybatis-generator-gui\0.3>java -jar my
batis-generator-gui-0.3.jar
mybatis-generator-gui-0.3.jar中没有主清单属性
`

**Comment by astarring** [comment]
请问你是使用什么命令构建的？

    git clone https://github.com/astarring/mybatis-generator-gui
    cd mybatis-generator-gui
    mvn jfx:jar

详情请参考：https://github.com/astarring/mybatis-generator-gui 自助构建

**Comment by baiyapeng** [comment]
可能是我弄错了，放在MyEclipse中运行正常，非常感谢您的回复。另外，大神辛苦了~

**Comment by astarring** [comment]
好的，不客气。

**Comment by albertshaw** [comment]
遇到同样的问题
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

用的命令是`mvn jfx:jar`, 也试了`mvn clean jfx:jar`  报错`mybatis-generator-gui-0.3.jar中没有主清单属性`

同样在eclipse里面直接运行MainUI.java不会报错, mvn命令打包方式有问题么？

**Comment by black-ant** [comment]
检测是否在该路径下 : mybatis-generator-gui\target\jfx\app
