### ISSUE TITLE
maven 打包报错

### ISSUE THREAD

**Issue by codeyuyu** [astarring/mybatis-generator-gui#12]
![qq 20160819145007](https://cloud.githubusercontent.com/assets/1551791/17801394/700f8e28-661c-11e6-9a49-93099d4b6de9.png)

**Comment by astarring** [comment]
请升级你的jdk至1.8版本的。请使用你的>java -version查看你当前的命令行版本。

**Comment by astarring** [comment]
java版本问题，关闭。
