### ISSUE TITLE
oralce数据库下如果用dba权限账号会选择系统中所有的表?

### ISSUE THREAD

**Issue by galaxist** [astarring/mybatis-generator-gui#13]
oralce数据库下如果用dba权限账号会选择系统中所有的表，并且是平铺没有树结构展示。

**Comment by astarring** [comment]
是的，会显示所有的表，你觉得如何更好呢。

**Comment by galaxist** [comment]
可以加个schema参数效果相当于
select * from all_tables where owner='schema'.
这样就指定了特定的用户.

**Comment by cnprinces** [comment]
ResultSet rs = md.getTables(null, config.getUsername().toUpperCase(), null, null);

**Comment by astarring** [comment]
已经按 @cnprinces 的方法做了，现在只显示账号拥有的表了。
