### ISSUE TITLE
能把字段的注释生成到实体类上面嘛？

### ISSUE THREAD

**Issue by wangjia2016** [astarring/mybatis-generator-gui#15]
能把数据库字段的注释生成到实体类上面嘛？
默认的注释丑爆了，而且是英文

![image](https://cloud.githubusercontent.com/assets/16084076/17995805/4502538e-6b97-11e6-8f65-685fafcfdeea.png)

**Comment by astarring** [comment]
已经支持啊，你勾上Use Columns Comments As Java Model Comments就可以了。

**Comment by astarring** [comment]
已经支持，关闭
