### ISSUE TITLE
运行成功 但没有生成相应的代码

### ISSUE THREAD

**Issue by wangwei418** [astarring/mybatis-generator-gui#19]
正常运行结束 也没有报错，但对应到目录下并没有生成任何文件

**Comment by astarring** [comment]
确保你的目前及包都存在，由于generator并不会报错（至少我目前没有发现会），所以这段逻辑并不在我的GUI控制之下，后面我看一下是否有更好的办法捕获目录不存在的情况。

**Comment by wangwei418** [comment]
我是直接运行的代码，看代码也没啥异常，目录肯定是存在的  目前还没找到什么问题

**Comment by astarring** [comment]
@cheney0214 已经帮忙增加了validation的逻辑，稍后几天发布。

**Comment by 274665843** [comment]
确实，配置应该没问题，也提示生成成功，但目标文件夹里什么都没有

**Comment by astarring** [comment]
@274665843 确认一下目录都存在吗？

**Comment by crazyrunsnail** [comment]
路径名对了就行了

**Comment by astarring** [comment]
新的develop版本文件不存在会自己提示生成相应的文件目录。
