### ISSUE TITLE
can't get left db tree

### ISSUE THREAD

**Issue by YDJX** [astarring/mybatis-generator-gui#2]
after I have downloaded and compiled project, I run the jar  . I get the gui, I connect my mysql db is success when I click 'test connect'. but I can't get the database tree on the left .

**Comment by astarring** [comment]
![qq20160704-0 2x](https://cloud.githubusercontent.com/assets/3505708/16548158/9ede8c6e-41b8-11e6-8ef0-3ac8168d4a3e.png)
You mean you double click left DB tree item and can't collapse it, right? Can you paste your log in your log folder in the project folder and any error you find please paste it out. 

And furthermore, I will release 0.3 version, and it will add customize column feature. Hope in this version resolve your problem. I version will release about Jul 6th.

**Comment by astarring** [comment]
I add some code to show the error, can you please pull latest develop branch and run it again. And show me the error log if it has.

**Comment by tobbychen** [comment]
actually I got the same error after click the button to save the connection, the error code was about the config file of dbConfig.xml. These xml files were mostly empty, do we need to fill in the DB information in this file?

**Comment by astarring** [comment]
What's your DB type, Oracle?

**Comment by tobbychen** [comment]
Mysql, and I was running this on Mac.


________________________________
发件人: Owen <notifications@github.com>
发送时间: 2016年7月6日 8:52
收件人: astarring/mybatis-generator-gui
抄送: tobbychen; Comment
主题: Re: [astarring/mybatis-generator-gui] can't get left db tree (#2)


What's your DB type, Oracle?

―

**Comment by astarring** [comment]
Can you please upload a snapshot into this issue thread which contains the error message.

**Comment by shevgao** [comment]
It's probably that you typed an invalid "Connection Name"(eg: 120) in New Connection dialogue. It checked the tag name when create an element. More detail, you can refer to com.sun.org.apache.xerces.internal.dom.createElement(String)

**Comment by astarring** [comment]
目前最新的分支应该已经解决此问题了。
