### ISSUE TITLE
首次运行成功后再次运行会提示TargetFolder路径异常，然后自动关闭

### ISSUE THREAD

**Issue by applecomb** [astarring/mybatis-generator-gui#21]
TargetFolder路径填的Maven的路径，src\main\java和src\main\resources，第一次运行成功，第二次打开CMD会报错，TargetFolder路径异常，把上次生成的config.xml文件删除再打开就好了，但是这样很麻烦，还是希望改进一下。

**Comment by astarring** [comment]
马上会改进的。

**Comment by astarring** [comment]
confix.xml已经不用了，请使用新的版本。
