### ISSUE TITLE
com.sun.javafx.css.parser.CSSParser declaration 警告: CSS Error parsing jar:file:

### ISSUE THREAD

**Issue by DavidZze** [astarring/mybatis-generator-gui#24]
../mybatis-generator-gui.jar!/style.css: expected series of <size> while parsing '-fx-border' at [14,16]
[INFO] [17:26:42.869] [JavaFX Application Thread] [] com.zzg.mybatis.generator.util.DbUtil.getConnectionUrlWithSchema:70 --> getConnectionUrlWithSchema, connection url: jdbc:oracle:thin:@10.211.55.4:1521:xe

环境：
Mac OSX10.11
问题描述：
打开 GUI 界面，输入数据库（Oracle）信息，Test 测试连接报如上错误。

**Comment by astarring** [comment]
请问你的数据库驱动的jar包你有选择吗？Oracle数据库目前可能是有一些问题，后面我再多测试测试Oracle数据库。

**Comment by astarring** [comment]
请忽略前端css的错误，并不影响软件的使用，是css中fx的语法有一些小的问题，最新版已经解决了。
