### ISSUE TITLE
启动就报错了，未能显示界面，详细错误如下，系统环境信息在最后

### ISSUE THREAD

**Issue by leeyong86** [astarring/mybatis-generator-gui#25]
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x000007feeb2a5c01, pid=4228, tid=0x0000000000000a20
# 
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [msvcr120.dll+0x95c01]
# 
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

---------------  T H R E A D  ---------------

Current thread (0x000000005a723000):  JavaThread "QuantumRenderer-0" daemon [_thread_in_native, id=2592, stack(0x000000005af60000,0x000000005b060000)]

siginfo: ExceptionCode=0xc000001d

---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7600 (6.1.7600.16385)

CPU:total 4 (2 cores per cpu, 2 threads per core) family 6 model 61 stepping 4, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, aes, clmul, erms, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 8291496k(4383660k free), swap 16581096k(12280572k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.92-b14) for windows-amd64 JRE (1.8.0_92-b14), built on Mar 31 2016 21:03:04 by "java_re" with MS VC++ 10.0 (VS2010)

time: Thu Sep 29 11:50:08 2016
elapsed time: 31 seconds (0d 0h 0m 31s)

**Comment by astarring** [comment]
从日志里看你好像使用的JRE，请使用JDK 1.8试试看。

**Comment by astarring** [comment]
jdk版本的问题，关闭问题
