### ISSUE TITLE
MyBatis Generator 1.3.4 扩展，可以设置 Mapper（Dao）后缀

### ISSUE THREAD

**Issue by fireworkDks** [astarring/mybatis-generator-gui#28]
MyBatis Generator 1.3.4 扩展

可以设置 Mapper（Dao）后缀

MyBatis Generator 简称 MBG，许多人在看 MyBatis Generator 详解 的时候问过我能不能设置 Mapper 的后缀为 Dao，在当时的情况下是没法解决的。但是到了 1.3.4 版本，MBG 在<table>元素上提供了一个 mapperName 的属性，可以设置生成的 Mapper 名字，使用方法如下：
`<table tableName="sys_store" mapperName="StoreDao"></table>`

大神能否更新成支持这样的设置呢?!

**Comment by fireworkDks** [comment]
<table tableName="sys_store" mapperName="StoreDao">
    <generatedKey column="id" sqlStatement="Mysql"/>
</table>

**Comment by astarring** [comment]
好的，下一个版本支持。

**Comment by fireworkDks** [comment]
@astarring 感谢大神~期待ing

**Comment by astarring** [comment]
这个代码已经提交，在开发版里面已经这个功能。另外一个feature由于涉及的字段太多，我还考虑一下界面如何放置这些字段。

**Comment by fireworkDks** [comment]
了解!!大神辛苦~~~`(*∩_∩*)′

**Comment by fireworkDks** [comment]
@astarring 刚试了下开发版!确实支持,成功生成! 
只是有点疑问,本来wiki中你说这个target folder目录一定要存在，否则代码将不会生成。
上个正式版本,我没填那个target folder,本地其实可以生成!
这个开发版本不填确实不行~~~估计这才是正确的打开方式!!   汗

**Comment by astarring** [comment]
@fireworkDks 之前的wiki是上一个版本的，目前这个版本v0.6.0还没有发布，加上最近也比较忙，所以没有好好测试一下，在发布版本之前都会解决好，谢谢你的意见。

**Comment by astarring** [comment]
@fireworkDks 新的develop版本已经支持了，抱歉这么久才回复你们。
