### ISSUE TITLE
考虑增加一下对 SQL Server 支持

### ISSUE THREAD

**Issue by Lumia1020** [astarring/mybatis-generator-gui#30]
考虑增加一下对 SQL Server 支持

**Comment by astarring** [comment]
SQL Server已经支持了。

**Comment by GongLe** [comment]
没发现支持SqlServer ,我下载最新的代码，Db Type 只有：MySql Oralce 、PostgreSQL三种选择哦！

**Comment by astarring** [comment]
@GongLe @Lumia1020 关键是我本地没有SQL Server的运行环境啊，你们要是有你们也可以贡献一点代码。

**Comment by astarring** [comment]
增加SQL Server的支持，还请多多帮忙测试测试一下。
