### ISSUE TITLE
Oracle连接失败

### ISSUE THREAD

**Issue by ppapfml** [astarring/mybatis-generator-gui#37]
点击Test Connection提示Connection failed

控制台提示信息：
[INFO] [10:09:26.392] [JavaFX Application Thread] [] com.zzg.mybatis.generator.u
til.DbUtil.getConnectionUrlWithSchema:70 --> getConnectionUrlWithSchema, connect
ion url: jdbc:oracle:thin:@localhost:1521:NORTHWIND
jdbc:oracle:thin:@localhost:1521:NORTHWIND

**Comment by astarring** [comment]
这个请自行调试，目前没有其他人说连接失败。看一下命令行是不是可以连接成功。
