### ISSUE TITLE
不删除之前生成的mapper.xml，重复生成的话tomcat启动会报错

### ISSUE THREAD

**Issue by liu870825yi** [astarring/mybatis-generator-gui#41]
生成实体的时候，如果不删除之前生成的mapper.xml的话，再次生成实体启动tomcat就会报错，这个能不能解决？希望能添加全选所有数据库表生成的功能，一个个表选然后生成太麻烦了

**Comment by astarring** [comment]
这个还请把原来的xml文件删除然后重新生成。全选数据库的功能暂时没有。
