### ISSUE TITLE
文件复制到项目中乱码

### ISSUE THREAD

**Issue by mykite** [astarring/mybatis-generator-gui#46]
生成的文件是什么编码，直接复制到UTF-8的项目中乱码，复制进去后改成gbk编码正常。如何配置生成文件的编码格式

**Comment by caideyuan** [comment]
经实践，生成的*Mapper.java，*Mapper.xml，*Example.java默认就是utf-8无BOM编码的，具体的实体类文件需要自己转编码，不知新版本是否已Fix该Bug？

**Comment by mykite** [comment]
![image](https://cloud.githubusercontent.com/assets/9413389/22921329/195b860a-f2d4-11e6-8e5b-e10bad309a91.png) 不清楚我之前拉下来代码生成下来是gbk的可能和使用电脑编码有关加了段代码就好了

**Comment by astarring** [comment]
我本地Windows测试了一下，生成的文件就是UTF-8编码的。请你提供的环境和截图我好方便排查问题。

**Comment by mykite** [comment]
额， 我刚删除也好了，不知道为啥
