### ISSUE TITLE
model屬性註釋亂碼

### ISSUE THREAD

**Issue by shinesoft** [astarring/mybatis-generator-gui#5]
生成的model屬性中文註釋全是亂碼，項目是UTF-8編碼的。
另外無法控制是否生成示例代碼。

**Comment by astarring** [comment]
请问你的mysql是UTF-8的编码吗？另外是否生成示例代码是什么意思？

**Comment by xiachunhang** [comment]
我也是乱码

**Comment by astarring** [comment]
我发了一个新的小版本，请更新最新的代码看是否解决你们的问题。

**Comment by astarring** [comment]
请新版本两位还有没有乱码的问题 @xiachunhang  @shinesoft

**Comment by astarring** [comment]
关闭此问题
