### ISSUE TITLE
压缩包中，没有 mybatis-generator-gui.jar

### ISSUE THREAD

**Issue by HeroOnline** [astarring/mybatis-generator-gui#50]
方法一: 下载的zip包
解压zip包，如果安装好了JRE或者JDK 8，直接cd至软件目录运行

java -jar mybatis-generator-gui.jar

压缩包中，没有 mybatis-generator-gui.jar

**Comment by astarring** [comment]
请自助构建一下吧，现在github对上次的文件大小有现在，所以后面的版本没有提供zip包的下载了。
