### ISSUE TITLE
SelectColumns能否允许设置JDBCType

### ISSUE THREAD

**Issue by caideyuan** [astarring/mybatis-generator-gui#56]

**Comment by caideyuan** [comment]
针对表里面某些特殊用途的为text类型的字段，需要设置：jdbcType="VARCHAR"，而不是：jdbcType="LONGVARCHAR"。能否在“SelectColumns”界面开放JDBC Type列设置？

**Comment by astarring** [comment]
将在v0.7.3中提供吧

**Comment by astarring** [comment]
![image](https://cloud.githubusercontent.com/assets/3505708/26522359/786eac00-4331-11e7-862f-55407eb15345.png)
已经提供
