### ISSUE TITLE
Oracle报错NO suitable driver found 

### ISSUE THREAD

**Issue by LeafToDus** [astarring/mybatis-generator-gui#57]
oracle版本：Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - Production
![image](https://cloud.githubusercontent.com/assets/16411636/23009332/601700ba-f450-11e6-9001-0796f526824e.png)

**Comment by tujiuquan** [comment]
那个连接的驱动可能和你的Oracle版本不匹配，建议你换个别的版本驱动试试。

**Comment by astarring** [comment]
@tujiuquan 新版本使用自定义的ClassLoader，应该没有此问题了。
