### ISSUE TITLE
可否添加对postgreSql的支持？

### ISSUE THREAD

**Issue by Tinet-wangll** [astarring/mybatis-generator-gui#6]
如题

**Comment by astarring** [comment]
好的，如有需求，我后面支持一下postgreSql，不过本人并没有使用过postgreSql，所以后面开发过程中有什么问题你支持一下我。有任何进展我会在这个issue中回复。

**Comment by Tinet-wangll** [comment]
之前用了3年mysql，也是刚开始学习postgreSql。

**Comment by astarring** [comment]
v0.5.0已经支持了PostgreSQL, 请更新最新的代码测试是否可行，我本地已经测试通过。

**Comment by Tinet-wangll** [comment]
为你点赞！

**Comment by astarring** [comment]
不客气，有什么问题可以再提。
