### ISSUE TITLE
建议给model添加个toString的方法

### ISSUE THREAD

**Issue by MidnightFiend** [astarring/mybatis-generator-gui#61]
之前一直在用的方法 ，自己感觉比较简洁

@Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this,
                ToStringStyle.MULTI_LINE_STYLE);
    }

**Comment by meixl** [comment]
我也想说这个来着orz

**Comment by astarring** [comment]
这个主意好

**Comment by chengs2035** [comment]
应该要增加一个输入的地方，能够选择性的去增加自定义的函数。

**Comment by astarring** [comment]
@MidnightFiend @meixl @chengs2035 
v0.8.4已经添加了此配置，使用了Mybatis generator官方的插件
