### ISSUE TITLE
关于重新生成文件的小 Issue。

### ISSUE THREAD

**Issue by tujiuquan** [astarring/mybatis-generator-gui#63]
如果对数据库的同一个table生成文件，以前存在的文件不会被删除，而继续在原来生成的文件内容后面最佳内容。例如，我原来已经对某个table生成了一个  mapper.xml，后来table里面的字段修改了一下，我继续对这个table 生成一下 mapper.xml ，原文件若存在于指定的目录之下，则会把生成的内容继续最佳在原文本的内容后面。我觉得应该在IO流写入是设置覆盖。

**Comment by astarring** [comment]
这个是个好建议，后面会更新改进的。

**Comment by astarring** [comment]
mybatis-generator本身不支持覆盖xml文件，所以暂时没有好办法去覆盖它。详情请参考：
http://www.mybatis.org/generator/running/runningWithMaven.html 
http://stackoverflow.com/questions/43245041/how-could-let-mybatis-generator-overwriting-the-already-generated-mapper-xml
