### ISSUE TITLE
配置保存问题

### ISSUE THREAD

**Issue by tonyBrantOne** [astarring/mybatis-generator-gui#67]
第一遍  连接完数据库 调试成功后  可以用。下一次再启动项目，数据库连接就失效了，要重新连接。
然后类的路径也要每次启动都要重新配置感觉好麻烦。可以把这两个保存起来，以后每次启动，就不用重新配了。

**Comment by astarring** [comment]
@tonyBrantOne 已经有保存配置的功能了。
