### ISSUE TITLE
对添加时间与分页插件的支持

### ISSUE THREAD

**Issue by vieze0** [astarring/mybatis-generator-gui#7]
工具很好用，后台管理的增删改查基本不用写了， 现在有2个问题。
1。是添加一条记录的添加时间的支持能否addtime,默认设置为now(),或者提供其他可以修改的方式，源码比较底层，看了挺久摸不出头绪，生成文件能否修改呢。求一份指导文档、
2.  另一个是对于分页插件的支持。我这边用的是网上的demo 所有类都是用page<?>  一个对象包装的，楼主用的是什么呢？能有一份项目的demo 就参考就好了，
本人QQ ：568854545.如果有时间指导的话，加我QQ,或者留下联系方式，再次感谢！

**Comment by astarring** [comment]
你好，以下是一个关于一个查询WorkOrderAction的例子。希望对你有帮助


     workOrderNo = 123456;
     WorkOrderActionExample example = new WorkOrderActionExample();
     example.createCriteria().andWorkOrderNoEqualTo(workOrderNo);
     example.setOffset(100);
     example.setLimit(10);
     List<WorkOrderAction> actions = actionMapper.selectByExample(example);
     return actions == null ? Collections.emptyList() : actions;

**Comment by astarring** [comment]
关闭此问题
