### ISSUE TITLE
sqlite3.db的Git管理

### ISSUE THREAD

**Issue by nagisun** [astarring/mybatis-generator-gui#73]
resources下的sqlite3.db应该需要上传至Git吧，config下的不传。如果是的话gitignore的设置需要更新。

**Comment by astarring** [comment]
目前已经是这样的啊，resources有sqlite3.db，config下面的已经被.gitignore了。
![image](https://cloud.githubusercontent.com/assets/3505708/25413929/b9b60576-2a60-11e7-86ac-cc360c5ff0e2.png)
