### ISSUE TITLE
无法自动构建代码

### ISSUE THREAD

**Issue by simpleSOA** [astarring/mybatis-generator-gui#79]
在执行 mvn jfx:jfx.jar这步骤报错
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.5.0:jar (default-cli) on project mybatis-generator-gui: Execution default-cli of goal com.zenjava:javafx-maven-plugin:8.5.0:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.5.0 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path E:\java8/../lib/ant-javafx.jar -> [Help 1]

**Comment by astarring** [comment]
是```mvn jfx:jar```，不是 mvn jfx:jfx.jar
