### ISSUE TITLE
一个事务内实体主键未生产

### ISSUE THREAD

**Issue by cheney0214** [astarring/mybatis-generator-gui#8]
一个事务内，当我的业务逻辑依赖新实体主键时，发现主键未生产。
业务场景，如新建用户组并为其分配组员：
1、创建用户组；
2、建立用户组与用户关系，依赖创建的用户组的主键；此时发现用户组的主键未生产。

**Comment by astarring** [comment]
你好，你要的功能在Mybatis中是配置一个generateKeys，目前mybatis generator已经有支持，请参考：http://www.mybatis.org/generator/configreference/generatedKey.html，非常感谢你的意见，我会在下一个版本中加入这个feature。

**Comment by liu870825yi** [comment]
主键加了吗？现在生成还是没有主键喔

**Comment by astarring** [comment]
@liu870825yi @cheney0214 新的develop分支已经添加了，只要在GeneratedKeys输入框中输入主键的名称，例如id，然后生成的代码就有主键了。
