### ISSUE TITLE
配置保存再次进入时驱动没有添加

### ISSUE THREAD

**Issue by leexuechuan** [astarring/mybatis-generator-gui#81]
` public static List<String> getTableNames(DatabaseConfig config) throws Exception {

        String url = getConnectionUrlWithSchema(config);
        _LOG.info("getTableNames, connection url: {}", url);
       //此处需要设置驱动？
        if("Oracle".equals(config.getDbType())){
        	Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
        }else if ("MySql".equals(config.getDbType())) {
        	Class.forName("com.mysql.jdbc.Driver").newInstance();
		}else {
			Class.forName("org.postgresql.Driver").newInstance();
		}

        Connection conn = DriverManager.getConnection(url, config.getUsername(), config.getPassword());
        DatabaseMetaData md = conn.getMetaData();
        ResultSet rs = md.getTables(null, config.getUsername().toUpperCase(), null, null);
        List<String> tables = new ArrayList<>();
        while (rs.next()) {
            tables.add(rs.getString(3));
        }
        return tables;
    }`

**Comment by astarring** [comment]
新版本0.8.0以上采用自定义的ClassLoader，所以应该不再有问题了。
