### ISSUE TITLE
能否支持Oracle

### ISSUE THREAD

**Issue by XShandow** [astarring/mybatis-generator-gui#9]

**Comment by XShandow** [comment]
如题

**Comment by astarring** [comment]
原则上都是支持的，不过我并没有测试过，如果不行会在接下二个星期左右的时间支持。

**Comment by astarring** [comment]
今日我已经测试本地连接成功，后面如果生成代码也成功的话我就会push oralce版本的代码上来。

**Comment by astarring** [comment]
已经在最近的v0.4.0版本支持了，请下载最近版本测试一下。如果有任何问题请告诉我。
