### ISSUE TITLE
对于同一个表，点击多次“代码生成”，会在实体类中产生多个serialVersionUID

### ISSUE THREAD

**Issue by ghost** [astarring/mybatis-generator-gui#92]
![tim 20170706154757](https://user-images.githubusercontent.com/19161054/27900863-825ec6c8-6262-11e7-823d-5ae66bf4e5f8.png)

**Comment by inke3c** [comment]
不是同一个表多次也会生成多个
private static final long serialVersionUID = 1L;

**Comment by astarring** [comment]
已经解决
