### ISSUE TITLE
能否添加queryAll方法来获取表中所有字段信息？

### ISSUE THREAD

**Issue by Cheava** [astarring/mybatis-generator-gui#93]
有了这个gui工具，确实提高了生产力，给你们32个赞！
目前使用中，感觉缺少一个queryAll方法来获取所有字段，不知道在后面版本中可否加入？
另外，在#88f1696 中src/main/java/com/zzg/mybatis/generator/plugins/DbRemarksCommentGenerator.java里line 90的"@Talbe"注解应该为“@Table”。
最后，谢谢你们写出来的工具！

**Comment by Cheava** [comment]
今天才了解到工具是基于mybatis-genertor的，所以也不能强求有queryAll方法。

**Comment by astarring** [comment]
谢谢你的指正，已经修正。正如你讲的，是由于基于mybatis-genertor，如果要queryAll, 传入一个没有任何条件的Example就OK了。
