### ISSUE TITLE
运行 mvn jfx:jar 报错，说插件不存在

### ISSUE THREAD

**Issue by zhangmin032011** [astarring/mybatis-generator-gui#95]
运行 **mvn jfx:jar**  报错，说插件不存在
![error](https://user-images.githubusercontent.com/7947897/28611051-1b094686-721d-11e7-8127-d6f5e817ba7c.png)

**Comment by astarring** [comment]
是你的本地mvn私服里面没有相应的jar包

**Comment by astarring** [comment]
请使用maven官方的repository
