### ISSUE TITLE
[BUG]数据库连接没问题，点击生成代码提示canot resolve classpath entry

### ISSUE THREAD

**Issue by xiuqianli1996** [astarring/mybatis-generator-gui#97]
![image](https://user-images.githubusercontent.com/29425257/28863705-9816c962-779c-11e7-9849-be817a2428c1.png)

**Comment by kevinlinit** [comment]
同问

**Comment by astarring** [comment]
已经解决，注意是没有同时兼容好IDE和jfx运行两种情况导致的问题。请更新最新版本的代码 @kevinlinit @xiuqianli1996
